name: testJaguar
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: Hakeem Oriola <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
 path: ^1.4.1
 jaguar: ^2.4.12
 jaguar_mongo: ^2.4.1
 jaguar_reflect: ^2.4.1
 jaguar_serializer: ^2.2.5
 json_annotation: ^2.0.0

dev_dependencies:
  test: ^1.0.0
  json_serializable: ^2.0.0
  build_runner: '>=0.8.10 <2.0.0'
  build_web_compilers: '>=0.3.6 <2.0.0'
